[project]
name = "li2200-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas",
    "pyproj",
    "pyvista",
    "panel",
    "trame",
    "trame-vtk",
    "trame-vuetify",
]

[project.scripts]
li2200-viewer = "li2200tools.viewer_app:main"
